# Generated by Django 5.2.7 on 2025-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislog',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysislog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
